using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;


[RealtimeModel]
public partial class RibbonPointModel {
    [RealtimeProperty(1, true)]
    private Vector3 _position;

    [RealtimeProperty(2, true)]
    private Quaternion _rotation = Quaternion.identity; 


}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RibbonPointModel : RealtimeModel {
    public UnityEngine.Vector3 position {
        get {
            return _postionProperty.value;
        }
        set {
            if (_postionProperty.value == value) return;
            _postionProperty.value = value;
            InvalidateReliableLength();
        }
    }
    
    public UnityEngine.Quaternion rotation {
        get {
            return _rotationProperty.value;
        }
        set {
            if (_rotationProperty.value == value) return;
            _rotationProperty.value = value;
            InvalidateReliableLength();
        }
    }
    
    public enum PropertyID : uint {
        Postion = 1,
        Rotation = 2,
    }
    
    #region Properties
    
    private ReliableProperty<UnityEngine.Vector3> _postionProperty;
    
    private ReliableProperty<UnityEngine.Quaternion> _rotationProperty;
    
    #endregion
    
    public RibbonPointModel() : base(null) {
        _postionProperty = new ReliableProperty<UnityEngine.Vector3>(1, _position);
        _rotationProperty = new ReliableProperty<UnityEngine.Quaternion>(2, _rotation);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _postionProperty.UnsubscribeCallback();
        _rotationProperty.UnsubscribeCallback();
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _postionProperty.WriteLength(context);
        length += _rotationProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _postionProperty.Write(stream, context);
        writes |= _rotationProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Postion: {
                    changed = _postionProperty.Read(stream, context);
                    break;
                }
                case (uint) PropertyID.Rotation: {
                    changed = _rotationProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _position = position;
        _rotation = rotation;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
